### ISSUE TITLE
TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by bartonhammond** [rickypc/selenium-page-object-generator#24]
I did install w/ `npm install selenium-page-object-generator`

Run time:

```
/projects/wisnet/gitProjects/temp$ node_modules/.bin/selenium-page-object-generator -t java -n MySite -s source.html
(node:49793) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
/Users/barton/projects/wisnet/gitProjects/temp/node_modules/selenium-page-object-generator/bin/generate.js:100
            window.close();
                  ^

TypeError: Cannot read property 'close' of undefined
    at Object.done (/Users/barton/projects/wisnet/gitProjects/temp/node_modules/selenium-page-object-generator/bin/generate.js:100:19)
    at reportInitError (/Users/barton/projects/wisnet/gitProjects/temp/node_modules/jsdom/lib/jsdom.js:384:12)
    at ReadStream.resourceLoader.readFile (/Users/barton/projects/wisnet/gitProjects/temp/node_modules/jsdom/lib/jsdom.js:161:9)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at fs.js:1956:12
    at FSReqWrap.oncomplete (fs.js:123:15)
~/projects/wisnet/gitProjects/temp$ 
```

**Comment by bartonhammond** [comment]
Not needed...
