### ISSUE TITLE
Need help running from command line

### ISSUE THREAD

**Issue by bartonhammond** [rickypc/selenium-page-object-generator#25]
Per Readme, I entered `gulp` - I don't see any `build` or `dist`

```(master)$ gulp
Loading Modules: 1701.695ms
[14:48:54] Using gulpfile ~/projects/wisnet/gitProjects/selenium-page-object-generator/gulpfile.js
[14:48:54] Starting 'clean'...
```

**Comment by bartonhammond** [comment]
Once I did `npm link` , I can run from command line but not successfully.
So  I did a "view source" on browser and saved as `myfile.html`.
Then did following:

```
ojects/wisnet/gitProjects/selenium-page-object-generator (master)$ selenium-page-object-generator -t java -n barton -s myfile.html 
(node:50049) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
/Users/barton/projects/wisnet/gitProjects/selenium-page-object-generator/bin/generate.js:97
            throw ex;
            ^

TypeError: Cannot read property 'setDefaultValues' of undefined
    at Object.done (/Users/barton/projects/wisnet/gitProjects/selenium-page-object-generator/bin/generate.js:85:35)
    at process.nextTick (/Users/barton/projects/wisnet/gitProjects/selenium-page-object-generator/node_modules/jsdom/lib/jsdom.js:271:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by bartonhammond** [comment]
Ok - the command is `gulp chrome`
Then
* remove the Extension from Chrome 
* then load with `chrome://extensions/` 
    * using `load unpacked extension` 
    * navigate to the `build\chrome` to reinstall extension
